name: Bump casks

on:
  workflow_dispatch:
  schedule:
    # Every day at 3am
    - cron: "0 3 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

env:
  HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}

jobs:
  bump:
    name: Bump casks
    runs-on: ubuntu-24.04
    steps:
      - name: Configure git user
        uses: tidylabs/action-git-config-user@v2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: tee -a "$GITHUB_ENV" < .devcontainer/homebrew.env

      - name: Setup Homebrew
        run: .devcontainer/setup.sh

      - name: Bump casks
        run: brew bump --open-pr --no-fork --tap "$GITHUB_REPOSITORY"
