name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  style:
    name: Check style
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: tee -a "$GITHUB_ENV" < .devcontainer/homebrew.env

      - name: Setup Homebrew
        run: .devcontainer/setup.sh

      - name: Style check
        run: brew style "$GITHUB_REPOSITORY"
